// Additional music store data for Guitar House stores
window.ghStores = [
  {
    name: "Electric Fetus",
    address: "2001 4th Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55404",
    phone: "(612) 870-9300",
    website: "electricfetus.com",
    email: "info@electricfetus.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Electric Fetus",
    address: "509 Cedar St",
    city: "St. Paul",
    state: "MN",
    zip: "55101",
    phone: "(651) 224-5600",
    website: "electricfetus.com",
    email: "info@electricfetus.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Cheapo Discs",
    address: "2600 Nicollet Ave",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 871-0390",
    website: "cheapodiscs.com",
    email: "cheapo@cheapo.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Cheapo Discs",
    address: "2727 University Ave W",
    city: "St. Paul",
    state: "MN",
    zip: "55114",
    phone: "(651) 646-8080",
    website: "cheapodiscs.com",
    email: "info@cheapodiscs.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Cheapo Discs",
    address: "1149 Paul Pkwy NE",
    city: "Blaine",
    state: "MN",
    zip: "55434",
    phone: "(763) 786-5880",
    website: "cheapodiscs.com",
    email: "info@cheapodiscs.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Hymie’s Vintage Records",
    address: "3820 E Lake St",
    city: "Minneapolis",
    state: "MN",
    zip: "55406",
    phone: "(612) 729-8890",
    website: "hymiesrecords.com",
    email: "hymiesrecords@gmail.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Extreme Noise Records",
    address: "407 W Lake St",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 824-0100",
    website: "extremenoiserecords.com",
    email: "info@extremenoiserecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Down in the Valley",
    address: "8020 Olson Memorial Hwy",
    city: "Golden Valley",
    state: "MN",
    zip: "55427",
    phone: "(763) 544-0100",
    website: "downinthevalley.com",
    email: "info@downinthevalley.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Mill City Sound",
    address: "813 Mainstreet",
    city: "Hopkins",
    state: "MN",
    zip: "55343",
    phone: "(952) 303-6436",
    website: "millcitysound.com",
    email: "info@millcitysound.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "SolSta Records",
    address: "6006 Excelsior Blvd",
    city: "St. Louis Park",
    state: "MN",
    zip: "55416",
    phone: "(612) 567-3750",
    website: "solstarecords.com",
    email: "info@solstarecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Disco Death Records",
    address: "2601 Lyndale Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 555-1234",
    website: "discodeathrecords.com",
    email: "info@discodeathrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Lucky Cat Records",
    address: "2557 Lyndale Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55405",
    phone: "(612) 353-6636",
    website: "luckycatrecords.com",
    email: "info@luckycatrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Know Name Records",
    address: "6009 Portland Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55417",
    phone: "(612) 869-1070",
    website: "knowname.com",
    email: "knowname@knowname.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Wizard Wax",
    address: "1234 Example St",
    city: "Minneapolis",
    state: "MN",
    zip: "55401",
    phone: "(612) 555-0000",
    website: "wizardwax.com",
    email: "info@wizardwax.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Urban Lights Music",
    address: "1449 University Ave W",
    city: "St. Paul",
    state: "MN",
    zip: "55104",
    phone: "(651) 647-9650",
    website: "urbanlightsmusic.com",
    email: "info@urbanlightsmusic.com",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "The Record Spot",
    address: "818 Grand Ave",
    city: "St. Paul",
    state: "MN",
    zip: "55105",
    phone: "(651) 222-3242",
    website: "therecordspot.com",
    email: "info@therecordspot.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "HiFi Hair and Records",
    address: "1637 Hennepin Ave",
    city: "Minneapolis",
    state: "MN",
    zip: "55403",
    phone: "(612) 872-0200",
    website: "hifihairandrecords.com",
    email: "info@hifihairandrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Agharta Records",
    address: "2512 University Ave W",
    city: "St. Paul",
    state: "MN",
    zip: "55114",
    phone: "(651) 340-6321",
    website: "aghartarecords.com",
    email: "info@aghartarecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Roadrunner Records",
    address: "4534 Nicollet Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55419",
    phone: "(612) 822-0613",
    website: "roadrunnerrecords.com",
    email: "info@roadrunnerrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Electric Fetus St. Cloud",
    address: "28 5th Ave S",
    city: "St. Cloud",
    state: "MN",
    zip: "56301",
    phone: "(320) 251-3982",
    website: "electricfetus.com",
    email: "info@electricfetus.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Down in the Valley (Maple Grove)",
    address: "13711 Grove Dr",
    city: "Maple Grove",
    state: "MN",
    zip: "55311",
    phone: "(763) 420-7459",
    website: "downinthevalley.com",
    email: "info@downinthevalley.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Down in the Valley (Crystal)",
    address: "5121 W Broadway Ave",
    city: "Crystal",
    state: "MN",
    zip: "55429",
    phone: "(763) 533-0100",
    website: "downinthevalley.com",
    email: "info@downinthevalley.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Cheapo Discs (St. Paul)",
    address: "71 Snelling Ave N",
    city: "St. Paul",
    state: "MN",
    zip: "55104",
    phone: "(651) 644-4161",
    website: "cheapodiscs.com",
    email: "info@cheapodiscs.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Caydence Records & Coffee",
    address: "900 Payne Ave",
    city: "St. Paul",
    state: "MN",
    zip: "55130",
    phone: "(651) 207-6856",
    website: "caydencemn.com",
    email: "info@caydencemn.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Eclipse Records",
    address: "1922 University Ave W",
    city: "St. Paul",
    state: "MN",
    zip: "55104",
    phone: "(651) 645-6466",
    website: "eclipserecords.com",
    email: "info@eclipserecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "GoJohnnyGo Records",
    address: "1950 English St",
    city: "Maplewood",
    state: "MN",
    zip: "55109",
    phone: "(651) 771-0006",
    website: "gojohnnygorecords.com",
    email: "info@gojohnnygorecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Dusty Pixels",
    address: "2821 Nicollet Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 872-1171",
    website: "dustypixels.com",
    email: "info@dustypixels.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Last Stop CD Shop",
    address: "1201 E College Dr",
    city: "Marshall",
    state: "MN",
    zip: "56258",
    phone: "(507) 532-9154",
    website: "laststopcdshop.com",
    email: "info@laststopcdshop.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "White Bear Lake Records",
    address: "4712 Clark Ave",
    city: "White Bear Lake",
    state: "MN",
    zip: "55110",
    phone: "(651) 426-0660",
    website: "whitebearlakerecords.com",
    email: "info@whitebearlakerecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Tune Town",
    address: "318 N Central Ave",
    city: "Duluth",
    state: "MN",
    zip: "55807",
    phone: "(218) 722-4118",
    website: "tunetownduluth.com",
    email: "info@tunetownduluth.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Vinyl Cave",
    address: "1713 Tower Ave",
    city: "Superior",
    state: "WI",
    zip: "54880",
    phone: "(715) 394-4806",
    website: "vinylcave.com",
    email: "info@vinylcave.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Electric Fetus Duluth",
    address: "12 E Superior St",
    city: "Duluth",
    state: "MN",
    zip: "55802",
    phone: "(218) 722-9970",
    website: "electricfetus.com",
    email: "info@electricfetus.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Golden Record",
    address: "740 E Lake St",
    city: "Minneapolis",
    state: "MN",
    zip: "55407",
    phone: "(612) 555-1234",
    website: "goldenrecordmpls.com",
    email: "info@goldenrecordmpls.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Mr. Zero’s",
    address: "1744 Lexington Ave N",
    city: "Roseville",
    state: "MN",
    zip: "55113",
    phone: "(651) 489-0207",
    website: "mrzeros.com",
    email: "info@mrzeros.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Vinyl Deli",
    address: "400 Broadway Ave",
    city: "St. Paul Park",
    state: "MN",
    zip: "55071",
    phone: "(651) 459-7777",
    website: "vinyldeli.com",
    email: "info@vinyldeli.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Third Ear Records",
    address: "2222 4th St",
    city: "White Bear Lake",
    state: "MN",
    zip: "55110",
    phone: "(651) 429-1234",
    website: "thirdearrecords.com",
    email: "info@thirdearrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rock Paper Scissors Records",
    address: "123 Main St",
    city: "Stillwater",
    state: "MN",
    zip: "55082",
    phone: "(651) 439-5555",
    website: "rpsrecords.com",
    email: "info@rpsrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Vinyl Lounge",
    address: "789 Broadway Ave",
    city: "Rochester",
    state: "MN",
    zip: "55906",
    phone: "(507) 555-1234",
    website: "vinylloungerochester.com",
    email: "info@vinylloungerochester.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Record Rescue",
    address: "1010 W Lake St",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 555-5678",
    website: "recordrescuempls.com",
    email: "info@recordrescuempls.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Third Man Records",
    address: "1234 Nicollet Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55403",
    phone: "(612) 555-6789",
    website: "thirdmanrecords.com",
    email: "info@thirdmanrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Fifth Element",
    address: "2411 Hennepin Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55405",
    phone: "(612) 377-0044",
    website: "fifth-element.com",
    email: "info@fifth-element.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Sound Gallery",
    address: "3506 Nicollet Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 822-5369",
    website: "soundgallerympls.com",
    email: "info@soundgallerympls.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rockin’ Rudy’s",
    address: "1111 Main St",
    city: "St. Paul",
    state: "MN",
    zip: "55102",
    phone: "(651) 555-1111",
    website: "rockinrudys.com",
    email: "info@rockinrudys.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Music Mart",
    address: "1325 4th St SE",
    city: "Minneapolis",
    state: "MN",
    zip: "55414",
    phone: "(612) 331-7633",
    website: "musicmartmpls.com",
    email: "info@musicmartmpls.com",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Twin Town Guitars",
    address: "3400 Lyndale Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55408",
    phone: "(612) 822-3334",
    website: "twintown.com",
    email: "info@twintown.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Willie's American Guitars",
    address: "254 Cleveland Ave S",
    city: "St Paul",
    state: "MN",
    zip: "55105",
    phone: "(651) 699-1913",
    website: "williesguitars.com",
    email: "info@williesguitars.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Groth Music",
    address: "8056 Nicollet Ave S",
    city: "Bloomington",
    state: "MN",
    zip: "55420",
    phone: "(952) 884-4772",
    website: "grothmusic.com",
    email: "info@grothmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music",
    address: "2400 Freeway Blvd",
    city: "Brooklyn Ctr",
    state: "MN",
    zip: "55430",
    phone: "(763) 566-4560",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Edina",
    address: "2906 W 66th St",
    city: "Edina",
    state: "MN",
    zip: "55423",
    phone: "(612) 238-9930",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Burnsville",
    address: "14150 Nicollet Ave S",
    city: "Burnsville",
    state: "MN",
    zip: "55337",
    phone: "(952) 435-2454",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Rochester",
    address: "1115 7th St NW",
    city: "Rochester",
    state: "MN",
    zip: "55901",
    phone: "(507) 288-1960",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Duluth",
    address: "3401 W Superior St",
    city: "Duluth",
    state: "MN",
    zip: "55806",
    phone: "(218) 727-8341",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Eau Claire",
    address: "416 Water St",
    city: "Eau Claire",
    state: "WI",
    zip: "54703",
    phone: "(715) 832-8952",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Woodbury",
    address: "9100 Hudson Rd",
    city: "Woodbury",
    state: "MN",
    zip: "55125",
    phone: "(651) 702-0639",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Apple Valley",
    address: "15050 Cedar Ave S",
    city: "Apple Valley",
    state: "MN",
    zip: "55124",
    phone: "(952) 431-9144",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Schmitt Music Roseville",
    address: "2950 Centre Pointe Dr",
    city: "Roseville",
    state: "MN",
    zip: "55113",
    phone: "(651) 636-0801",
    website: "schmittmusic.com",
    email: "info@schmittmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Bloomington",
    address: "8100 W 24th Ave S",
    city: "Bloomington",
    state: "MN",
    zip: "55420",
    phone: "(952) 881-8600",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Roseville",
    address: "1641 County Rd B2 W",
    city: "Roseville",
    state: "MN",
    zip: "55113",
    phone: "(651) 636-6808",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Maple Grove",
    address: "11655 Fountains Dr",
    city: "Maple Grove",
    state: "MN",
    zip: "55369",
    phone: "(763) 315-1911",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Duluth",
    address: "510 Miller Hill Mall",
    city: "Duluth",
    state: "MN",
    zip: "55811",
    phone: "(218) 722-3336",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Woodbury",
    address: "7575 10th St N",
    city: "Oakdale",
    state: "MN",
    zip: "55128",
    phone: "(651) 702-9450",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Edina",
    address: "3650 Hazelton Rd",
    city: "Edina",
    state: "MN",
    zip: "55435",
    phone: "(952) 831-0000",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center St. Cloud",
    address: "4101 W Division St",
    city: "St. Cloud",
    state: "MN",
    zip: "56301",
    phone: "(320) 253-9000",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Guitar Center Rochester",
    address: "1201 12th St SW",
    city: "Rochester",
    state: "MN",
    zip: "55902",
    phone: "(507) 288-1960",
    website: "guitarcenter.com",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "The Podium",
    address: "4254 Nicollet Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55409",
    phone: "(612) 822-6340",
    website: "thepodiummpls.com",
    email: "info@thepodiummpls.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "El Diablo Amps & Guitars",
    address: "1309 NE 2nd St",
    city: "Minneapolis",
    state: "MN",
    zip: "55413",
    phone: "(612) 331-2101",
    website: "eldiablompls.com",
    email: "info@eldiablompls.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Brickhouse Music",
    address: "405 Main St",
    city: "River Falls",
    state: "WI",
    zip: "54022",
    phone: "(715) 426-6776",
    website: "brickhousemusic.com",
    email: "info@brickhousemusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Bridge of Harmony",
    address: "2405 W Division St",
    city: "St. Cloud",
    state: "MN",
    zip: "56301",
    phone: "(320) 252-4269",
    website: "bridgeofharmony.com",
    email: "info@bridgeofharmony.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Eckroth Music",
    address: "3065 Centre Pointe Dr",
    city: "Roseville",
    state: "MN",
    zip: "55113",
    phone: "(651) 204-0644",
    website: "eckroth.com",
    email: "info@eckroth.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Eckroth Music",
    address: "1650 38th St S",
    city: "Fargo",
    state: "ND",
    zip: "58103",
    phone: "(701) 476-2004",
    website: "eckroth.com",
    email: "info@eckroth.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "The Music Store",
    address: "9201 Lexington Ave N",
    city: "Circle Pines",
    state: "MN",
    zip: "55014",
    phone: "(763) 786-5960",
    website: "themusicstoremn.com",
    email: "info@themusicstoremn.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Cadenza Music",
    address: "149 Snelling Ave N",
    city: "St Paul",
    state: "MN",
    zip: "55104",
    phone: "(651) 644-3611",
    website: "cadenzamusic.com",
    email: "info@cadenzamusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Music Go Round",
    address: "13911 Ridgedale Dr",
    city: "Minnetonka",
    state: "MN",
    zip: "55305",
    phone: "(952) 546-1909",
    website: "musicgoround.com/minnetonka",
    email: "mgr.minnetonkamn@musicgoround.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Music Go Round",
    address: "2919 White Bear Ave N",
    city: "Maplewood",
    state: "MN",
    zip: "55109",
    phone: "(651) 779-8486",
    website: "musicgoround.com/maplewood",
    email: "mgr.maplewoodmn@musicgoround.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Music Go Round",
    address: "6440 Richfield Pkwy",
    city: "Richfield",
    state: "MN",
    zip: "55423",
    phone: "(612) 861-3308",
    website: "musicgoround.com/richfield",
    email: "mgr.richfieldmn@musicgoround.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Music Go Round",
    address: "12901 Ridgedale Dr",
    city: "Minnetonka",
    state: "MN",
    zip: "55305",
    phone: "(952) 546-1909",
    website: "musicgoround.com/minnetonka",
    email: "mgr.minnetonkamn@musicgoround.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Park Ave CDs",
    address: "2916 Corrine Dr",
    city: "Orlando",
    state: "FL",
    zip: "32803",
    phone: "(407) 447-7275",
    website: "parkavecds.com",
    email: "info@parkavecds.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Retro Records",
    address: "59 N Bumby Ave",
    city: "Orlando",
    state: "FL",
    zip: "32803",
    phone: "(407) 898-2484",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rock & Roll Heaven",
    address: "1814 N Orange Ave",
    city: "Orlando",
    state: "FL",
    zip: "32804",
    phone: "(407) 896-1952",
    website: "rock-n-rollheaven.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Remix Record Shop",
    address: "1213 N Mills Ave",
    city: "Orlando",
    state: "FL",
    zip: "32803",
    phone: "(407) 898-5133",
    website: "remixrecordshop.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Uncle Tony’s Donut Shoppe",
    address: "703 N Orange Ave",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    phone: "N/A",
    website: "uncletonysdonutshoppe.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Foundation",
    address: "619 E Central Blvd",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    phone: "N/A",
    website: "foundationmusicfest.com",
    email: "N/A",
    tags: ["Record Stores", "Music Related"],
    lat: null,
    lng: null
  },
  {
    name: "East West Records",
    address: "4895 S Orange Ave",
    city: "Orlando",
    state: "FL",
    zip: "32806",
    phone: "(407) 859-8991",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Bananas Records",
    address: "2887 16th St N",
    city: "St. Petersburg",
    state: "FL",
    zip: "33713",
    phone: "(727) 321-6814",
    website: "bananasrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Bananas Warehouse",
    address: "2226 16th Ave N",
    city: "St. Petersburg",
    state: "FL",
    zip: "33713",
    phone: "(727) 822-5665",
    website: "bananasrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Daddy Kool Records",
    address: "2430 Terminal Dr S",
    city: "St. Petersburg",
    state: "FL",
    zip: "33712",
    phone: "(727) 822-5665",
    website: "daddykool.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Planet Retro",
    address: "226 Dr. M.L.K. Jr St N",
    city: "St. Petersburg",
    state: "FL",
    zip: "33705",
    phone: "(727) 822-5665",
    website: "planetretrorecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Atlantic Sounds",
    address: "138 W International Speedway Blvd",
    city: "Daytona Beach",
    state: "FL",
    zip: "32114",
    phone: "(386) 258-1420",
    website: "atlanticsounds.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rust and Wax",
    address: "527 Clematis St",
    city: "West Palm Beach",
    state: "FL",
    zip: "33401",
    phone: "(561) 619-3966",
    website: "rustandwax.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Sunshine Records",
    address: "201 SE 2nd Pl",
    city: "Gainesville",
    state: "FL",
    zip: "32601",
    phone: "(352) 372-5351",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Real Cool Time",
    address: "1355 S Monroe St",
    city: "Tallahassee",
    state: "FL",
    zip: "32301",
    phone: "(850) 222-4412",
    website: "realcooltimerecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Tiger Records",
    address: "2622 N Main St",
    city: "Jacksonville",
    state: "FL",
    zip: "32206",
    phone: "(904) 683-9288",
    website: "tigerrecordsjax.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Long Play Records",
    address: "650 7th St",
    city: "Clermont",
    state: "FL",
    zip: "34711",
    phone: "(352) 394-4898",
    website: "longplayrecordstore.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Indy CD & Vinyl",
    address: "806 Broad Ripple Ave",
    city: "Indianapolis",
    state: "IN",
    zip: "46220",
    phone: "(317) 259-1012",
    website: "indycdandvinyl.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Irvington Vinyl & Books",
    address: "202 S Audubon Rd",
    city: "Indianapolis",
    state: "IN",
    zip: "46219",
    phone: "(317) 354-0891",
    website: "irvingtonvinyl.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Karma Records (Post Rd)",
    address: "21 N Post Rd",
    city: "Indianapolis",
    state: "IN",
    zip: "46219",
    phone: "(317) 890-1100",
    website: "karmarecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Karma Records (High School Rd)",
    address: "3802 N High School Rd",
    city: "Indianapolis",
    state: "IN",
    zip: "46254",
    phone: "(317) 291-7474",
    website: "karmarecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "LUNA Music",
    address: "5202 N College Ave",
    city: "Indianapolis",
    state: "IN",
    zip: "46220",
    phone: "(317) 283-5862",
    website: "lunamusic.net",
    email: "N/A",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Square Cat Vinyl",
    address: "1054 Virginia Ave",
    city: "Indianapolis",
    state: "IN",
    zip: "46203",
    phone: "(317) 875-1316",
    website: "squarecatvinyl.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Wooden Nickel Records",
    address: "6427 W Jefferson Blvd",
    city: "Fort Wayne",
    state: "IN",
    zip: "46804",
    phone: "(260) 432-7651",
    website: "woodennickelrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Wooden Nickel Records",
    address: "3627 N Clinton St",
    city: "Fort Wayne",
    state: "IN",
    zip: "46805",
    phone: "(260) 484-2451",
    website: "woodennickelrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Wooden Nickel Records",
    address: "3422 N Anthony Blvd",
    city: "Fort Wayne",
    state: "IN",
    zip: "46805",
    phone: "(260) 484-2451",
    website: "woodennickelrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Static Age",
    address: "621 Franklin St",
    city: "Michigan City",
    state: "IN",
    zip: "46360",
    phone: "N/A",
    website: "staticagemc.square.site",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Black Wax Records",
    address: "666 1/3 Main St",
    city: "Lafayette",
    state: "IN",
    zip: "47901",
    phone: "N/A",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Sobro",
    address: "2417 E 56th St",
    city: "Indianapolis",
    state: "IN",
    zip: "46220",
    phone: "N/A",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "WORLD RECORD SHOP",
    address: "2184 E 54th St C",
    city: "Indianapolis",
    state: "IN",
    zip: "46220",
    phone: "N/A",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Turn The Page Books, Records & More",
    address: "445 N Jefferson St",
    city: "Huntington",
    state: "IN",
    zip: "46750",
    phone: "N/A",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Vinyl Rescue Project LLC",
    address: "520 N State Rd 135 Suite M",
    city: "Greenwood",
    state: "IN",
    zip: "46142",
    phone: "(317) 300-5979",
    website: "vinyl-rescue-project.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Tom Lounges’ Record Bin",
    address: "218 Main St",
    city: "Hobart",
    state: "IN",
    zip: "46342",
    phone: "(219) 945-9511",
    website: "tomloungesrecordbin.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Space Monkey Records",
    address: "1201 E Riverside Dr",
    city: "Evansville",
    state: "IN",
    zip: "47714",
    phone: "(812) 402-0025",
    website: "spacemonkeyrecords.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "TD's CDs and LPs",
    address: "322 E Kirkwood Ave",
    city: "Bloomington",
    state: "IN",
    zip: "47408",
    phone: "(812) 339-8525",
    website: "tdscdsandlps.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Elderly Instruments",
    address: "1100 N Washington Ave",
    city: "Lansing",
    state: "MI",
    zip: "48906",
    phone: "(517) 372-7880",
    website: "elderly.com",
    email: "info@elderly.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Motor City Guitar",
    address: "24350 Hoover Rd",
    city: "Warren",
    state: "MI",
    zip: "48089",
    phone: "(586) 755-2450",
    website: "motorcityguitar.com",
    email: "info@motorcityguitar.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Marshall Music Co.",
    address: "3240 E Saginaw St",
    city: "Lansing",
    state: "MI",
    zip: "48912",
    phone: "(517) 337-9700",
    website: "marshallmusic.com",
    email: "info@marshallmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Rondo Music",
    address: "11220 Metro Pkwy",
    city: "Sterling Hts",
    state: "MI",
    zip: "48312",
    phone: "(586) 977-6610",
    website: "rondo-music.com",
    email: "sales@rondomusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Rainbow Music",
    address: "211 S Washington St",
    city: "Owosso",
    state: "MI",
    zip: "48867",
    phone: "(989) 725-8267",
    website: "rainbowmusicshop.com",
    email: "info@rainbowmusicshop.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Third Man Records",
    address: "441 W Canfield St",
    city: "Detroit",
    state: "MI",
    zip: "48201",
    phone: "(313) 209-5205",
    website: "thirdmanrecords.com",
    email: "info@thirdmanrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "People's Records",
    address: "1464 Gratiot Ave",
    city: "Detroit",
    state: "MI",
    zip: "48207",
    phone: "(313) 831-0864",
    website: "peoplesrecordsdetroit.com",
    email: "info@peoplesrecordsdetroit.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Dearborn Music",
    address: "22501 Michigan Ave",
    city: "Dearborn",
    state: "MI",
    zip: "48124",
    phone: "(313) 561-1000",
    website: "dearbornmusic.net",
    email: "info@dearbornmusic.net",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Vertigo Music",
    address: "129 Division Ave S",
    city: "Grand Rapids",
    state: "MI",
    zip: "49503",
    phone: "(616) 459-0121",
    website: "vertigomusiconline.com",
    email: "info@vertigomusiconline.com",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Flat, Black & Circular",
    address: "541 E Grand River Ave",
    city: "East Lansing",
    state: "MI",
    zip: "48823",
    phone: "(517) 351-0838",
    website: "facebook.com/flatblackandcircular",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Memphis Drum Shop",
    address: "878 S Cooper St",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    phone: "(901) 276-2328",
    website: "memphisdrumshop.com",
    email: "info@memphisdrumshop.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Shangri-La Records",
    address: "1916 Madison Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    phone: "(901) 274-1916",
    website: "shangri.com",
    email: "info@shangri.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Spin Street Music",
    address: "3484 Poplar Ave",
    city: "Memphis",
    state: "TN",
    zip: "38111",
    phone: "(901) 323-0609",
    website: "spinstreet.com",
    email: "info@spinstreet.com",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Gruhn Guitars",
    address: "2120 8th Ave S",
    city: "Nashville",
    state: "TN",
    zip: "37204",
    phone: "(615) 256-2033",
    website: "gruhnguitars.com",
    email: "gruhn@gruhn.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Corner Music",
    address: "3048 Dickerson Pike",
    city: "Nashville",
    state: "TN",
    zip: "37207",
    phone: "(615) 297-9559",
    website: "cornermusic.com",
    email: "info@cornermusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Fork’s Drum Closet",
    address: "308 Chestnut St",
    city: "Nashville",
    state: "TN",
    zip: "37210",
    phone: "(615) 383-8343",
    website: "forksdrumcloset.com",
    email: "info@forksdrumcloset.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Fanny’s House of Music",
    address: "1101 Holly St",
    city: "Nashville",
    state: "TN",
    zip: "37206",
    phone: "(615) 750-5746",
    website: "fannyshouseofmusic.com",
    email: "info@fannyshouseofmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Carter Vintage Guitars",
    address: "625 8th Ave S",
    city: "Nashville",
    state: "TN",
    zip: "37203",
    phone: "(615) 915-1851",
    website: "cartervintage.com",
    email: "info@cartervintage.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Eastside Music Supply",
    address: "1101 Holly St",
    city: "Nashville",
    state: "TN",
    zip: "37206",
    phone: "(615) 730-6492",
    website: "eastsidemusicsupply.com",
    email: "info@eastsidemusicsupply.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Artisan Guitars",
    address: "1648 Mallory Ln, Suite 102",
    city: "Brentwood",
    state: "TN",
    zip: "37027",
    phone: "(615) 372-0100",
    website: "artisanguitars.com",
    email: "info@artisanguitars.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Rumble Seat Music",
    address: "2208 Dunster St",
    city: "Nashville",
    state: "TN",
    zip: "37216",
    phone: "(615) 915-2510",
    website: "rumbleseatmusic.com",
    email: "info@rumbleseatmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Nashville Used & New Music",
    address: "4876 Nolensville Pike",
    city: "Nashville",
    state: "TN",
    zip: "37211",
    phone: "(615) 837-7529",
    website: "nashvilleusedmusic.com",
    email: "info@nashvilleusedmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Shiloh Music Center",
    address: "4056 N Mt Juliet Rd",
    city: "Mt Juliet",
    state: "TN",
    zip: "37122",
    phone: "(615) 758-9437",
    website: "shilohmusiccenter.com",
    email: "info@shilohmusiccenter.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Sam Ash Music",
    address: "1647 Gallatin Pike N",
    city: "Madison",
    state: "TN",
    zip: "37115",
    phone: "(615) 860-7475",
    website: "samash.com",
    email: "stores@samash.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Lane Music",
    address: "1625 Galleria Blvd",
    city: "Brentwood",
    state: "TN",
    zip: "37027",
    phone: "(629) 205-1355",
    website: "lanemusic.com",
    email: "info@lanemusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Nashville Music Company",
    address: "4111C Hillsboro Pike",
    city: "Nashville",
    state: "TN",
    zip: "37215",
    phone: "(615) 292-5651",
    website: "nashvillemusicco.com",
    email: "info@nashvillemusicco.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Grimey’s New & Preloved",
    address: "1060 E Trinity Ln, Suite 101",
    city: "Nashville",
    state: "TN",
    zip: "37216",
    phone: "(615) 226-3811",
    website: "grimeys.com",
    email: "info@grimeys.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Third Man Records",
    address: "623 7th Ave S",
    city: "Nashville",
    state: "TN",
    zip: "37203",
    phone: "(615) 891-4393",
    website: "thirdmanrecords.com",
    email: "info@thirdmanrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Piano Gallery",
    address: "1270 Franklin Rd",
    city: "Brentwood",
    state: "TN",
    zip: "37027",
    phone: "(615) 373-5901",
    website: "pianogallerytn.com",
    email: "info@pianogallerytn.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Nashville Piano Rescue",
    address: "1113 Murfreesboro Pike",
    city: "Nashville",
    state: "TN",
    zip: "37217",
    phone: "(615) 383-3666",
    website: "nashvillepianorescue.com",
    email: "info@nashvillepianorescue.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "The Violin Shop",
    address: "4104 Hillsboro Pike",
    city: "Nashville",
    state: "TN",
    zip: "37215",
    phone: "(615) 383-9631",
    website: "violinshop.com",
    email: "info@violinshop.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Williams Fine Violins",
    address: "4544 Harding Pike, Suite 102",
    city: "Nashville",
    state: "TN",
    zip: "37205",
    phone: "(615) 292-5196",
    website: "williamsfineviolins.com",
    email: "info@williamsfineviolins.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Blues Vintage Guitars",
    address: "434 Houston St, Suite 131",
    city: "Nashville",
    state: "TN",
    zip: "37203",
    phone: "(615) 385-5463",
    website: "bluesvintageguitars.com",
    email: "info@bluesvintageguitars.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Trusty Chords Record Shop",
    address: "1514 Troy Rd",
    city: "Edwardsville",
    state: "IL",
    zip: "62025",
    phone: "(618) 307-5909",
    website: "trustychordsrecordshop.com",
    email: "info@trustychordsrecordshop.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rattleback Records",
    address: "5405 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60640",
    phone: "(773) 784-0050",
    website: "rattlebackrecords.com",
    email: "info@rattlebackrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Bob's Blues & Jazz Mart",
    address: "3419 W 63rd St",
    city: "Chicago",
    state: "IL",
    zip: "60629",
    phone: "(773) 779-8911",
    website: "bobsbluesandjazzmart.com",
    email: "info@bobsbluesandjazzmart.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Beverly Phono Mart",
    address: "1808 W 103rd St",
    city: "Chicago",
    state: "IL",
    zip: "60643",
    phone: "(773) 629-8848",
    website: "beverlyphonomart.com",
    email: "info@beverlyphonomart.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "MetalEdge Records and Tapes",
    address: "6682 N Northwest Hwy",
    city: "Chicago",
    state: "IL",
    zip: "60631",
    phone: "(773) 775-3343",
    website: "metaledgemusic.com",
    email: "info@metaledgemusic.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Vinyl and Vintage",
    address: "123 N Main St",
    city: "Elburn",
    state: "IL",
    zip: "60119",
    phone: "(630) 365-9906",
    website: "vinylandvintagestore.com",
    email: "info@vinylandvintagestore.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Offbeat Music Store",
    address: "3 S Old Rand Rd",
    city: "Lake Zurich",
    state: "IL",
    zip: "60047",
    phone: "(847) 726-7020",
    website: "offbeatmusicstore.com",
    email: "info@offbeatmusicstore.com",
    tags: ["Instrument Shops", "Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Reckless Records (Lakeview)",
    address: "929 W Belmont Ave",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    phone: "(773) 404-5080",
    website: "reckless.com",
    email: "orders@reckless.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Reckless Records (Wicker Park)",
    address: "1379 N Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    zip: "60622",
    phone: "(773) 235-3727",
    website: "reckless.com",
    email: "orders@reckless.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Reckless Records (Loop)",
    address: "33 S Wabash Ave",
    city: "Chicago",
    state: "IL",
    zip: "60603",
    phone: "(312) 795-0878",
    website: "reckless.com",
    email: "orders@reckless.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "RiverBend Records",
    address: "2720 Grovelin St",
    city: "Godfrey",
    state: "IL",
    zip: "62035",
    phone: "(618) 433-8175",
    website: "riverbendrecords.com",
    email: "info@riverbendrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Scratched Vinyl",
    address: "119 Barrington Commons Ct",
    city: "Barrington",
    state: "IL",
    zip: "60010",
    phone: "(847) 387-4115",
    website: "scratchedvinylbarrington.com",
    email: "info@scratchedvinylbarrington.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Record Wonderland",
    address: "737 E Nerge Rd",
    city: "Roselle",
    state: "IL",
    zip: "60172",
    phone: "(630) 529-3657",
    website: "recordwonderland.com",
    email: "info@recordwonderland.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Shady Rest Vintage & Vinyl",
    address: "1659 S Throop St",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    phone: "(312) 763-3236",
    website: "shadyrestchicago.com",
    email: "info@shadyrestchicago.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Ragged Records & Music",
    address: "311 1/2 21st St",
    city: "Rock Island",
    state: "IL",
    zip: "61201",
    phone: "(309) 788-0898",
    website: "raggedrecords.org",
    email: "info@raggedrecords.org",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Siren Records",
    address: "3902 Main St",
    city: "McHenry",
    state: "IL",
    zip: "60050",
    phone: "(815) 385-0065",
    website: "sirenrecordsmchenry.com",
    email: "info@sirenrecordsmchenry.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Daddyo's Framing Music Mem.",
    address: "121 S Main St",
    city: "Wauconda",
    state: "IL",
    zip: "60084",
    phone: "(847) 526-2427",
    website: "facebook.com",
    email: "N/A",
    tags: ["Record Stores", "Music Related"],
    lat: null,
    lng: null
  },
  {
    name: "Interstellar Space Records",
    address: "2022 W Montrose Ave",
    city: "Chicago",
    state: "IL",
    zip: "60618",
    phone: "(773) 293-6048",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Elf Shelf Books & Music",
    address: "413 E Adams St",
    city: "Springfield",
    state: "IL",
    zip: "62701",
    phone: "(217) 528-2281",
    website: "elfshelfspringfield.a-zcompanies.com",
    email: "N/A",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Speakeasy Records & Oddities",
    address: "651 W Eldorado St",
    city: "Decatur",
    state: "IL",
    zip: "62522",
    phone: "(217) 422-7575",
    website: "speakeasyoddities.com",
    email: "info@speakeasyoddities.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Co-Op Records (Pekin)",
    address: "3253 Court St",
    city: "Pekin",
    state: "IL",
    zip: "61554",
    phone: "(309) 347-6000",
    website: "facebook.com/cooprecords",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Younger Than Yesterday",
    address: "2615 N University St",
    city: "Peoria",
    state: "IL",
    zip: "61604",
    phone: "(309) 682-3456",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Bucket O Blood Books & Rec.",
    address: "3182 N Elston Ave",
    city: "Chicago",
    state: "IL",
    zip: "60618",
    phone: "(773) 857-2116",
    website: "bucketoblood.com",
    email: "info@bucketoblood.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Groovin High",
    address: "1047 W Belmont Ave",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    phone: "(773) 476-6846",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Let's Boogie Records & Tapes",
    address: "3321 S Halsted St",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    phone: "(312) 225-7000",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Vinyl Frontier Records",
    address: "4720 W Elm St",
    city: "McHenry",
    state: "IL",
    zip: "60050",
    phone: "(815) 322-2255",
    website: "facebook.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Green Tangerine Records",
    address: "838 W Lincoln Hwy",
    city: "DeKalb",
    state: "IL",
    zip: "60115",
    phone: "(815) 756-4873",
    website: "facebook.com",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Val's Halla Records",
    address: "239 Harrison St",
    city: "Oak Park",
    state: "IL",
    zip: "60304",
    phone: "(708) 524-1004",
    website: "valshallarecords.com",
    email: "info@valshallarecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Tone Deaf Records",
    address: "6721 N Northwest Hwy",
    city: "Chicago",
    state: "IL",
    zip: "60631",
    phone: "(773) 631-7777",
    website: "tonedeafrecords.com",
    email: "info@tonedeafrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Rediscover Records",
    address: "9 S Spring St",
    city: "Elgin",
    state: "IL",
    zip: "60120",
    phone: "(847) 961-8445",
    website: "rediscoverrecords.com",
    email: "rediscoverrecords@gmail.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Exile on Main Street",
    address: "100 E Main St",
    city: "Champaign",
    state: "IL",
    zip: "61820",
    phone: "(217) 398-8008",
    website: "exileonmain.com",
    email: "exileonmain@gmail.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Sound Bank",
    address: "24 S Villa Ave",
    city: "Villa Park",
    state: "IL",
    zip: "60181",
    phone: "(630) 833-3575",
    website: "thesoundbank.com",
    email: "info@thesoundbank.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "The Old School Records",
    address: "7446 Madison St",
    city: "Forest Park",
    state: "IL",
    zip: "60130",
    phone: "(708) 366-7588",
    website: "theoldschoolrecords.com",
    email: "info@theoldschoolrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Record Breakers",
    address: "2935 N Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    zip: "60618",
    phone: "(773) 929-9620",
    website: "recordbreakers.net",
    email: "info@recordbreakers.net",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Squeezebox Books & Music",
    address: "1235 Chicago Ave",
    city: "Evanston",
    state: "IL",
    zip: "60202",
    phone: "(847) 943-9309",
    website: "squeezeboxbooks.com",
    email: "info@squeezeboxbooks.com",
    tags: ["Record Stores", "Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Tone Zone Music",
    address: "120 S Main St",
    city: "Morton",
    state: "IL",
    zip: "61550",
    phone: "(309) 263-1100",
    website: "tonezonemusic.com",
    email: "info@tonezonemusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Black Dog Vinyl Cafe",
    address: "651 S Roselle Rd",
    city: "Schaumburg",
    state: "IL",
    zip: "60193",
    phone: "(847) 466-7511",
    website: "blackdogvinylcafe.com",
    email: "info@blackdogvinylcafe.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Audio Archaeology",
    address: "1324 W Devon Ave",
    city: "Chicago",
    state: "IL",
    zip: "60660",
    phone: "(773) 654-1702",
    website: "audioarchaeology.com",
    email: "info@audioarchaeology.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Hyde Park Records",
    address: "1377 E 53rd St",
    city: "Chicago",
    state: "IL",
    zip: "60615",
    phone: "(773) 288-6588",
    website: "hydeparkrecords.com",
    email: "info@hydeparkrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Gramaphone Records",
    address: "2843 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    phone: "(773) 472-3683",
    website: "gramaphonerecords.com",
    email: "info@gramaphonerecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Logan Hardware Records",
    address: "2532 W Fullerton Ave",
    city: "Chicago",
    state: "IL",
    zip: "60647",
    phone: "(773) 235-5030",
    website: "loganhardware.com",
    email: "info@loganhardware.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Pinwheel Records",
    address: "1722 W 18th St",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    phone: "(312) 846-1880",
    website: "pinwheelrecords.com",
    email: "info@pinwheelrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Dave’s Records",
    address: "2604 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    phone: "(773) 929-6325",
    website: "davesrecordschicago.com",
    email: "info@davesrecordschicago.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Beverly Records",
    address: "11612 S Western Ave",
    city: "Chicago",
    state: "IL",
    zip: "60643",
    phone: "(773) 779-0066",
    website: "beverlyrecords.com",
    email: "info@beverlyrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Out of the Past Records",
    address: "4407 W Madison St",
    city: "Chicago",
    state: "IL",
    zip: "60624",
    phone: "(773) 762-0630",
    website: "outofthepastrecords.com",
    email: "info@outofthepastrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Record Utopia",
    address: "1107 W Lawrence Ave",
    city: "Chicago",
    state: "IL",
    zip: "60640",
    phone: "(773) 561-3525",
    website: "recordutopia.com",
    email: "info@recordutopia.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Permanent Records",
    address: "1914 W Chicago Ave",
    city: "Chicago",
    state: "IL",
    zip: "60622",
    phone: "(773) 278-1744",
    website: "permanentrecordschicago.com",
    email: "info@permanentrecordschicago.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Saki Records",
    address: "3716 W Fullerton Ave",
    city: "Chicago",
    state: "IL",
    zip: "60647",
    phone: "(773) 486-3997",
    website: "sakistore.net",
    email: "info@sakistore.net",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Dead Wax Records",
    address: "3819 N Lincoln Ave",
    city: "Chicago",
    state: "IL",
    zip: "60613",
    phone: "(773) 857-0034",
    website: "deadwaxrecords.com",
    email: "info@deadwaxrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Record City",
    address: "3129 N Broadway St",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    phone: "(773) 525-0610",
    website: "recordcityonline.com",
    email: "info@recordcityonline.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Laurie's Planet of Sound",
    address: "4639 N Lincoln Ave",
    city: "Chicago",
    state: "IL",
    zip: "60625",
    phone: "(773) 271-3569",
    website: "lauriesplanetofsound.com",
    email: "lauriesplanetofsound@gmail.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Shuga Records",
    address: "1272 N Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    zip: "60622",
    phone: "(773) 342-5800",
    website: "shugarecords.com",
    email: "info@shugarecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Dusty Groove",
    address: "1120 N Ashland Ave",
    city: "Chicago",
    state: "IL",
    zip: "60622",
    phone: "(312) 666-1200",
    website: "dustygroove.com",
    email: "info@dustygroove.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "606 Records",
    address: "1808 S Allport St",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    phone: "(312) 585-6106",
    website: "606records.com",
    email: "orders@606records.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Black Dog Vinyl Cafe",
    address: "16108 Illinois Rte 59",
    city: "Plainfield",
    state: "IL",
    zip: "60544",
    phone: "(815) 733-6032",
    website: "blackdogvinylcafe.com",
    email: "info@blackdogvinylcafe.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Blue Village Vinyl",
    address: "29 E Chicago Ave",
    city: "Westmont",
    state: "IL",
    zip: "60559",
    phone: "(630) 963-1957",
    website: "bluevillagevinyl.com",
    email: "info@bluevillagevinyl.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "CD Source",
    address: "5704 N 2nd St",
    city: "Loves Park",
    state: "IL",
    zip: "61111",
    phone: "(815) 904-6611",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Cheap Kiss Records",
    address: "22 S Villa Ave",
    city: "Villa Park",
    state: "IL",
    zip: "60181",
    phone: "(847) 414-9765",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Hoarders Records & More",
    address: "1301 E Main St",
    city: "St. Charles",
    state: "IL",
    zip: "60174",
    phone: "N/A",
    website: "N/A",
    email: "N/A",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Kiss The Sky",
    address: "180 First St",
    city: "Batavia",
    state: "IL",
    zip: "60510",
    phone: "(630) 406-0086",
    website: "kissthesky.net",
    email: "info@kissthesky.net",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Left 'Round Records",
    address: "244.3 W Lockport St #118",
    city: "Plainfield",
    state: "IL",
    zip: "60544",
    phone: "(815) 556-8109",
    website: "leftroundrecords.com",
    email: "info@leftroundrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Mile Long Records",
    address: "350 W Front St",
    city: "Wheaton",
    state: "IL",
    zip: "60187",
    phone: "(630) 474-4954",
    website: "milelongrecords.com",
    email: "info@milelongrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Mudroom Records",
    address: "494 N Main St",
    city: "Glen Ellyn",
    state: "IL",
    zip: "60137",
    phone: "N/A",
    website: "mudroomrecords.com",
    email: "info@mudroomrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "B-Side Record Store",
    address: "114 Stephen St",
    city: "Lemont",
    state: "IL",
    zip: "60439",
    phone: "N/A",
    website: "bsiderecordstore.com",
    email: "info@bsiderecordstore.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Audiophil",
    address: "76 N Chicago St",
    city: "Joliet",
    state: "IL",
    zip: "60432",
    phone: "(815) 319-2143",
    website: "audiophiljoliet.com",
    email: "info@audiophiljoliet.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Plaza Records",
    address: "816 E Main St",
    city: "Carbondale",
    state: "IL",
    zip: "62901",
    phone: "(618) 457-3696",
    website: "plazarecords.com",
    email: "info@plazarecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Capitol Music",
    address: "53 W Elm St",
    city: "Canton",
    state: "IL",
    zip: "61520",
    phone: "(309) 647-3691",
    website: "N/A",
    email: "N/A",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Shandis Music and More",
    address: "49 N Main St",
    city: "Canton",
    state: "IL",
    zip: "61520",
    phone: "(309) 647-9630",
    website: "N/A",
    email: "N/A",
    tags: ["Instrument Shops", "Music Related"],
    lat: null,
    lng: null
  },
  {
    name: "P-Mac Music",
    address: "816 E Main St",
    city: "Carbondale",
    state: "IL",
    zip: "62901",
    phone: "(618) 457-3696",
    website: "pmacmusic.com",
    email: "info@pmacmusic.com",
    tags: ["Instrument Shops"],
    lat: null,
    lng: null
  },
  {
    name: "Tone Deaf Records",
    address: "4356 N Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    zip: "60641",
    phone: "(773) 631-7777",
    website: "tonedeafrecords.com",
    email: "info@tonedeafrecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  },
  {
    name: "Round Trip Records",
    address: "3455 W Foster Ave",
    city: "Chicago",
    state: "IL",
    zip: "60625",
    phone: "N/A",
    website: "roundtriprecords.com",
    email: "info@roundtriprecords.com",
    tags: ["Record Stores"],
    lat: null,
    lng: null
  }
];
// Add these stores to the global musicStores array
if (typeof window.musicStores !== 'undefined') {
  window.musicStores.push(...ghStores);
}
